defmodule Mix.Tasks.Phx.Gen.EmailPreferences.Remove.FileRemover do
  @moduledoc """
  Handles file removal for email preferences cleanup.
  """

  @doc """
  Returns a list of all files that were generated by phx.gen.email_preferences.
  """
  def get_files_to_remove(binding) do
    context_app = binding[:context_app]
    _app_module = binding[:app_module]
    _web_module = binding[:web_module]

    context_lib_path = Mix.Phoenix.context_lib_path(context_app, "")
    web_prefix = Mix.Phoenix.web_path(context_app)

    [
      # Context files
      Path.join([context_lib_path, "email_preferences.ex"]),
      Path.join([context_lib_path, "email_preferences/user_preference.ex"]),
      Path.join([context_lib_path, "email_preferences/preference_history.ex"]),
      Path.join([context_lib_path, "email_preferences/telemetry.ex"]),
      Path.join([context_lib_path, "email_preferences/config.ex"]),

      # LiveView files
      Path.join([web_prefix, "live/email_preferences_live.ex"]),
      Path.join([web_prefix, "live/unsubscribe_live.ex"]),
      Path.join([web_prefix, "live/email_preferences_modal.ex"]),
      Path.join([web_prefix, "hooks/email_preferences_hook.ex"]),

      # Component files
      Path.join([web_prefix, "components/email_preferences_components.ex"]),

      # Config file
      "priv/email_preferences.json",

      # Test files
      "test/#{context_app}_web/live/email_preferences_live_test.exs",
      "test/#{context_app}_web/live/unsubscribe_live_test.exs",
      "test/#{context_app}/email_preferences_test.exs"
    ]
  end

  @doc """
  Returns a list of migration files related to email preferences.
  """
  def get_migration_files do
    (Path.wildcard("priv/repo/migrations/*_create_user_email_preferences.exs") ++
       Path.wildcard("priv/repo/migrations/*_create_email_preference_history.exs"))
    |> Enum.sort(:desc)
  end

  @doc """
  Removes all files in the given list.
  """
  def remove_files(files) do
    {removed_count, removed_files} =
      Enum.reduce(files, {0, []}, fn file, {count, acc} ->
        if File.exists?(file) do
          File.rm!(file)
          Mix.shell().info("  Removed #{file}")
          {count + 1, [file | acc]}
        else
          {count, acc}
        end
      end)

    {removed_count, Enum.reverse(removed_files)}
  end

  @doc """
  Removes empty directories that may have been created.
  """
  def cleanup_empty_directories(binding) do
    context_app = binding[:context_app]
    context_lib_path = Mix.Phoenix.context_lib_path(context_app, "")

    email_prefs_dir = Path.join([context_lib_path, "email_preferences"])

    if File.dir?(email_prefs_dir) && directory_empty?(email_prefs_dir) do
      File.rmdir!(email_prefs_dir)
      Mix.shell().info("  Removed empty directory #{email_prefs_dir}")
    end
  end

  defp directory_empty?(dir) do
    case File.ls(dir) do
      {:ok, []} -> true
      {:ok, _} -> false
      {:error, _} -> false
    end
  end
end
