defmodule Mix.Tasks.Phx.Gen.EmailPreferences.Remove do
  @shortdoc "Removes email preferences functionality from a Phoenix app"

  @moduledoc """
  Removes the email preferences functionality that was generated by
  `mix phx.gen.email_preferences`.

  This task will:

  1. Roll back the migrations (if they've been run)
  2. Remove all generated files
  3. Display instructions for manually removing any added routes

  ## Usage

      $ mix phx.gen.email_preferences.remove

  ## Options

    * `--no-rollback` - Skip rolling back migrations (only remove files)
    * `--force` - Don't prompt for confirmation

  ## Examples

      $ mix phx.gen.email_preferences.remove

      $ mix phx.gen.email_preferences.remove --no-rollback

      $ mix phx.gen.email_preferences.remove --force

  """
  use Mix.Task

  alias Mix.Tasks.Phx.Gen.EmailPreferences.Remove.{FileRemover, MigrationRollback}

  @requirements ["app.config"]

  def run(args) do
    validate_project_structure!()

    opts = parse_options(args)
    binding = build_binding()

    files_to_remove = FileRemover.get_files_to_remove(binding)
    migration_files = FileRemover.get_migration_files()

    display_removal_summary(files_to_remove, migration_files, opts.no_rollback)

    unless opts.force do
      confirm_removal!()
    end

    unless opts.no_rollback do
      rollback_migrations_if_needed(migration_files)
    end

    remove_all_files(files_to_remove, migration_files)
    FileRemover.cleanup_empty_directories(binding)
    display_manual_cleanup_instructions()
  end

  defp validate_project_structure! do
    if Mix.Project.umbrella?() do
      Mix.raise("""
      mix phx.gen.email_preferences.remove must be invoked from within your
      *_web application root directory
      """)
    end
  end

  defp parse_options(args) do
    {opts, _parsed, _invalid} =
      OptionParser.parse(args,
        strict: [no_rollback: :boolean, force: :boolean]
      )

    %{
      no_rollback: Keyword.get(opts, :no_rollback, false),
      force: Keyword.get(opts, :force, false)
    }
  end

  defp build_binding do
    context_app = Mix.Phoenix.context_app()
    base_module = Macro.camelize(Atom.to_string(context_app))

    [
      context_app: context_app,
      app_module: base_module,
      web_module: "#{base_module}Web"
    ]
  end

  defp display_removal_summary(files_to_remove, migration_files, no_rollback) do
    Mix.shell().info("")
    Mix.shell().info("This will remove the following files:")
    Mix.shell().info("")

    if length(migration_files) > 0 && !no_rollback do
      Mix.shell().info("Migrations to roll back:")

      for file <- migration_files do
        Mix.shell().info("  #{file}")
      end

      Mix.shell().info("")
    end

    Mix.shell().info("Files to remove:")

    for file <- files_to_remove do
      if File.exists?(file) do
        Mix.shell().info("  #{file}")
      end
    end

    Mix.shell().info("")
  end

  defp confirm_removal! do
    unless Mix.shell().yes?("Do you want to proceed?") do
      Mix.shell().info("Aborted.")
      exit(:normal)
    end
  end

  defp rollback_migrations_if_needed(migration_files) do
    if length(migration_files) > 0 do
      Mix.shell().info("")
      Mix.shell().info("Rolling back migrations...")

      if MigrationRollback.migrations_applied?(migration_files) do
        MigrationRollback.rollback(migration_files)
        Mix.shell().info("Migrations rolled back successfully.")
      else
        Mix.shell().info("Migrations have not been applied, skipping rollback.")
      end
    end
  end

  defp remove_all_files(files_to_remove, migration_files) do
    Mix.shell().info("")
    Mix.shell().info("Removing files...")

    all_files = files_to_remove ++ migration_files
    {removed_count, _} = FileRemover.remove_files(all_files)

    Mix.shell().info("")
    Mix.shell().info("Removed #{removed_count} files.")
  end

  defp display_manual_cleanup_instructions do
    Mix.shell().info("")

    Mix.shell().info("""
    ========================================
    Manual Cleanup Required
    ========================================

    Please remove the following from your router.ex file:

    1. Remove from authenticated routes:

       live "/settings/email-preferences", EmailPreferencesLive, :index

    2. Remove from public routes:

       live "/unsubscribe/:token", UnsubscribeLive, :show

    3. Remove the modal hook from your authenticated live_session:

       - Remove EmailPreferencesHook from on_mount
       - Remove the <.live_component> for EmailPreferencesModal from your layout

    4. If you added any opt_in_checkbox components to forms, remove them.

    Email preferences have been removed!
    """)
  end
end
